import styles from './MainLayout.module.css'
import Head from 'next/head'

import { NavBar } from '../NavBar'

export const MainLayout = ({children}) => {
    return (
        <div className={styles.container}>
        <NavBar />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          {children}
        </main>
      </div>
      )
}
